pdclib = pdclib/functions/ctype/isspace.o \
pdclib/functions/stdlib/rand.o \
pdclib/functions/stdlib/labs.o \
pdclib/functions/stdlib/atoi.o \
pdclib/functions/stdlib/lldiv.o \
pdclib/functions/stdlib/strtoull.o \
pdclib/functions/stdlib/strtoll.o \
pdclib/functions/stdlib/exit.o \
pdclib/functions/stdlib/atol.o \
pdclib/functions/stdlib/strtoul.o \
pdclib/functions/stdlib/strtol.o \
pdclib/functions/stdlib/_Exit.o \
pdclib/functions/stdlib/ldiv.o \
pdclib/functions/stdlib/calloc.o \
pdclib/functions/stdlib/div.o \
pdclib/functions/stdlib/free.o \
pdclib/functions/stdlib/bsearch.o \
pdclib/functions/stdlib/abort.o \
pdclib/functions/stdlib/srand.o \
pdclib/functions/stdlib/realloc.o \
pdclib/functions/stdlib/qsort.o \
pdclib/functions/stdlib/malloc.o \
pdclib/functions/stdlib/atexit.o \
pdclib/functions/stdlib/abs.o \
pdclib/functions/stdlib/llabs.o \
pdclib/functions/stdlib/atoll.o \
pdclib/functions/stdio/sscanf.o \
pdclib/functions/stdio/fseek.o \
pdclib/functions/stdio/ftell.o \
pdclib/functions/stdio/printf.o \
pdclib/functions/stdio/scanf.o \
pdclib/functions/stdio/feof.o \
pdclib/functions/stdio/fputc.o \
pdclib/functions/stdio/fgetc.o \
pdclib/functions/stdio/vsscanf.o \
pdclib/functions/stdio/tmpnam.o \
pdclib/functions/stdio/snprintf.o \
pdclib/functions/stdio/puts.o \
pdclib/functions/stdio/gets.o \
pdclib/functions/stdio/sprintf.o \
pdclib/functions/stdio/fscanf.o \
pdclib/functions/stdio/vprintf.o \
pdclib/functions/stdio/fflush.o \
pdclib/functions/stdio/fsetpos.o \
pdclib/functions/stdio/vsprintf.o \
pdclib/functions/stdio/setbuf.o \
pdclib/functions/stdio/fopen.o \
pdclib/functions/stdio/fputs.o \
pdclib/functions/stdio/ungetc.o \
pdclib/functions/stdio/fread.o \
pdclib/functions/stdio/clearerr.o \
pdclib/functions/stdio/rename.o \
pdclib/functions/stdio/vfprintf.o \
pdclib/functions/stdio/fwrite.o \
pdclib/functions/stdio/rewind.o \
pdclib/functions/stdio/vsnprintf.o \
pdclib/functions/stdio/fprintf.o \
pdclib/functions/stdio/vfscanf.o \
pdclib/functions/stdio/perror.o \
pdclib/functions/stdio/setvbuf.o \
pdclib/functions/stdio/freopen.o \
pdclib/functions/stdio/ferror.o \
pdclib/functions/stdio/fgetpos.o \
pdclib/functions/stdio/fclose.o \
pdclib/functions/stdio/vscanf.o \
pdclib/functions/stdio/fgets.o \
pdclib/functions/string/memchr.o \
pdclib/functions/string/strstr.o \
pdclib/functions/string/strrchr.o \
pdclib/functions/string/strpbrk.o \
pdclib/functions/string/strcpy.o \
pdclib/functions/string/strspn.o \
pdclib/functions/string/strchr.o \
pdclib/functions/string/strcmp.o \
pdclib/functions/string/strncat.o \
pdclib/functions/string/strcat.o \
pdclib/functions/string/strxfrm.o \
pdclib/functions/string/memcmp.o \
pdclib/functions/string/strncmp.o \
pdclib/functions/string/strncpy.o \
pdclib/functions/string/strcspn.o \
pdclib/functions/string/memcpy.o \
pdclib/functions/string/strcoll.o \
pdclib/functions/string/memset.o \
pdclib/functions/string/memmove.o \
pdclib/functions/string/strerror.o \
pdclib/functions/string/strtok.o \
pdclib/functions/string/strlen.o \
pdclib/functions/ctype/tolower.o \
pdclib/functions/ctype/isspace.o \
pdclib/functions/inttypes/imaxabs.o \
pdclib/functions/inttypes/strtoimax.o \
pdclib/functions/inttypes/imaxdiv.o \
pdclib/functions/inttypes/strtoumax.o \
pdclib_platform/functions/stdlib/getenv.o \
pdclib_platform/functions/stdlib/system.o \
pdclib_platform/functions/signal/raise.o \
pdclib_platform/functions/signal/signal.o \
pdclib_platform/functions/stdio/remove.o \
pdclib_platform/functions/stdio/tmpfile.o \
pdclib_platform/functions/_PDCLIB/fillbuffer.o \
pdclib_platform/functions/_PDCLIB/_Exit.o \
pdclib_platform/functions/_PDCLIB/stdinit.o \
pdclib_platform/functions/_PDCLIB/close.o \
pdclib_platform/functions/_PDCLIB/flushbuffer.o \
pdclib_platform/functions/_PDCLIB/allocpages.o \
pdclib_platform/functions/_PDCLIB/open.o \
pdclib_platform/functions/_PDCLIB/rename.o \
pdclib_platform/functions/_PDCLIB/seek.o
